# Hourly build, cache not allowed
name: Nightly build on master

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Rust cache
      - name: Rust cargo cache
        uses: actions/cache@v1
        env:
          cache-name: cache-rust-cargo
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      # Rust toolchain
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Rust cargo
      - run: cargo build --release