name: "Pre Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Rust cache
      - name: Rust cargo cache
        uses: actions/cache@v1
        env:
          cache-name: cache-rust-cargo
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      # Rust toolchain
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Rust cargo
      - run: cargo build --release

      # Draft Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true